replicaCount: 1

image:
  repository: 788210522308.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: "frontend-8c397"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-pull-secret

podAnnotations:
  environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
