replicaCount: 3

image:
  repository: leonardtia/articles
  tag: "develop"
  pullPolicy: IfNotPresent

podAnnotations:
  environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
